{
 "title": "Pizza Dashboard",
 "time": { "from": "2026-03-05T14:09:31.632Z", "to": "2026-03-05T20:09:31.632Z" },
 "panels": [
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) * 60\n",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"GET\"}[5m])) * 60\n",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"PUT\"}[5m])) * 60\n",
     "legendFormat": "Put"
    },
    {
     "expr": "sum(rate(http_requests_total{ method=\"POST\"}[5m])) * 60\n",
     "legendFormat": "Post"
    },
    {
     "expr": "sum(rate(http_requests_total{method=\"DELETE\"}[5m])) * 60\n",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_request_duration.*\", route=\"/api/order/\", method=\"POST\"}[5m]))\n/\nsum(rate({__name__=~\"http_requests.*\", route=\"/api/order/\", method=\"POST\"}[5m]))\n",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum({__name__=~\"http_active_requests.*\"})\n",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum({__name__=~\"pizza_purchase_latency.*\", result=\"success\"})\n/\nsum({__name__=~\"pizza_purchases.*\", result=\"success\"})\n",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage Percentage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"system_cpu_usage.*\"}[15m])\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(system_memory_usage_percent)\n",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pizza Purchases ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(pizza_items_total{result=\"success\"}[5m])) * 60\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(pizza_purchases_total{result=\"failure\"}[5m])) * 60\n",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"http_requests.*\", route=~\"/api/auth/?\", method=\"PUT\", status=~\"2..\"}[1h])) or on() vector(0)\n",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase({__name__=~\"http_requests.*\", route=~\"/api/auth/?\", method=\"PUT\", status!~\"2..\"}[1h])) or on() vector(0)\n\n\n\n\n",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"pizza_purchase_revenue.*\", result=\"success\"}[1h]))\n\n\n\n\n",
     "legendFormat": "BitCoin"
    }
   ]
  }
 ]
}